# Copyright 2026 Element Creations Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only

rules:
  cache-poisoning:
    ignore:
      # This job do not release any artifact, we do not care about cache poisoning
      - matrix-tools.yml:33
      # This job do not release any artifact, we do not care about cache poisoning
      - matrix-tools.yml:56
